spring:
  application:
    name: licensing-service
  profiles:
    active: dev
  config:
    import: "configserver:http://localhost:8071"
  jpa:
    hibernate:
      ddl-auto: create-drop
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    db:
      enabled: false
    diskspace:
      enabled: true
