server:
  port: 8071
spring:
  application:
    name: config-server
  profiles:
    active: native, git #, vault
  cloud:
    config:
      server:
#        encrypt.enabled: false
        native:
          search-locations: classpath:/config
        git:
          uri: https://github.com/OHHYUN/spring-microservice-in-action.git
          searchPaths: config
#        vault:
#          port: 8200
#          host: 127.0.0.1
#          kvVersion: 2
#          profile-separator: /
#          backend: licensing-service
